{ '.list-group': { marginBottom: '20px', paddingLeft: 0 },
  '.list-group-item': 
   [ { position: 'relative',
       display: 'block',
       padding: '10px 15px',
       marginBottom: '-1px',
       backgroundColor: '@list-group-bg',
       border: '1px solid @list-group-border',
       '&:first-child': { '$mixin': { '.border-top-radius': [ '@list-group-border-radius' ] } },
       '&:last-child': 
        { marginBottom: 0,
          '$mixin': { '.border-bottom-radius': [ '@list-group-border-radius' ] } } },
     {},
     '&.disabled,   &.disabled:hover,   &.disabled:focus': { backgroundColor: '@list-group-disabled-bg',
       color: '@list-group-disabled-color',
       cursor: '@cursor-disabled',
       '.list-group-item-heading': { color: 'inherit' },
       '.list-group-item-text': { color: '@list-group-disabled-text-color' } },
     '&.active,   &.active:hover,   &.active:focus': { zIndex: 2,
       color: '@list-group-active-color',
       backgroundColor: '@list-group-active-bg',
       borderColor: '@list-group-active-border',
       '.list-group-item-heading,     .list-group-item-heading > small,     .list-group-item-heading > .small': { color: 'inherit' },
       '.list-group-item-text': { color: '@list-group-active-text-color' } } ],
  'a.list-group-item, button.list-group-item': 
   { color: '@list-group-link-color',
     '.list-group-item-heading': { color: '@list-group-link-heading-color' },
     '&:hover,   &:focus': 
      { textDecoration: 'none',
        color: '@list-group-link-hover-color',
        backgroundColor: '@list-group-hover-bg' } },
  'button.list-group-item': { width: '100%', textAlign: 'left' },
  '$mixin': 
   [ { '.list-group-item-variant': [ 'success', '@state-success-bg', '@state-success-text' ] },
     { '.list-group-item-variant': [ 'info', '@state-info-bg', '@state-info-text' ] },
     { '.list-group-item-variant': [ 'warning', '@state-warning-bg', '@state-warning-text' ] },
     { '.list-group-item-variant': [ 'danger', '@state-danger-bg', '@state-danger-text' ] } ],
  '.list-group-item-heading': { marginTop: 0, marginBottom: '5px' },
  '.list-group-item-text': { marginBottom: 0, lineHeight: 1.3 } }
