{ '.popover': 
   [ { position: 'absolute',
       top: 0,
       left: 0,
       zIndex: '@zindex-popover',
       display: 'none',
       maxWidth: '@popover-max-width',
       padding: '1px',
       '$mixin': 
        [ { '.reset-text': [ 0 ] },
          { '.box-shadow': [ '0 5px 10px rgba(0,0,0,.2)' ] } ],
       fontSize: '@font-size-base',
       backgroundColor: '@popover-bg',
       backgroundClip: 'padding-box',
       border: 
        [ '1px solid @popover-fallback-border-color',
          '1px solid @popover-border-color' ],
       borderRadius: '@border-radius-large',
       '&.top': { marginTop: '-@popover-arrow-width' },
       '&.right': { marginLeft: '@popover-arrow-width' },
       '&.bottom': { marginTop: '@popover-arrow-width' },
       '&.left': { marginLeft: '-@popover-arrow-width' } },
     {},
     '&.top > .arrow': { left: '50%',
       marginLeft: '-@popover-arrow-outer-width',
       borderBottomWidth: 0,
       borderTopColor: 
        [ '@popover-arrow-outer-fallback-color',
          '@popover-arrow-outer-color' ],
       bottom: '-@popover-arrow-outer-width',
       '&:after': 
        { content: '" "',
          bottom: '1px',
          marginLeft: '-@popover-arrow-width',
          borderBottomWidth: 0,
          borderTopColor: '@popover-arrow-color' } },
     '&.right > .arrow': { top: '50%',
       left: '-@popover-arrow-outer-width',
       marginTop: '-@popover-arrow-outer-width',
       borderLeftWidth: 0,
       borderRightColor: 
        [ '@popover-arrow-outer-fallback-color',
          '@popover-arrow-outer-color' ],
       '&:after': 
        { content: '" "',
          left: '1px',
          bottom: '-@popover-arrow-width',
          borderLeftWidth: 0,
          borderRightColor: '@popover-arrow-color' } },
     '&.bottom > .arrow': { left: '50%',
       marginLeft: '-@popover-arrow-outer-width',
       borderTopWidth: 0,
       borderBottomColor: 
        [ '@popover-arrow-outer-fallback-color',
          '@popover-arrow-outer-color' ],
       top: '-@popover-arrow-outer-width',
       '&:after': 
        { content: '" "',
          top: '1px',
          marginLeft: '-@popover-arrow-width',
          borderTopWidth: 0,
          borderBottomColor: '@popover-arrow-color' } },
     '&.left > .arrow': { top: '50%',
       right: '-@popover-arrow-outer-width',
       marginTop: '-@popover-arrow-outer-width',
       borderRightWidth: 0,
       borderLeftColor: 
        [ '@popover-arrow-outer-fallback-color',
          '@popover-arrow-outer-color' ],
       '&:after': 
        { content: '" "',
          right: '1px',
          borderRightWidth: 0,
          borderLeftColor: '@popover-arrow-color',
          bottom: '-@popover-arrow-width' } } ],
  '.popover-title': 
   { margin: 0,
     padding: '8px 14px',
     fontSize: '@font-size-base',
     backgroundColor: '@popover-title-bg',
     borderBottom: '1px solid darken(@popover-title-bg, 5%)',
     borderRadius: '(@border-radius-large - 1) (@border-radius-large - 1) 0 0' },
  '.popover-content': { padding: '9px 14px' },
  '.popover > .arrow': 
   [ { '&,   &:after': 
        { position: 'absolute',
          display: 'block',
          width: 0,
          height: 0,
          borderColor: 'transparent',
          borderStyle: 'solid' } },
     { borderWidth: '@popover-arrow-outer-width' } ],
  '.popover > .arrow:after': { borderWidth: '@popover-arrow-width', content: '""' } }
