{ '.tooltip': 
   [ { position: 'absolute',
       zIndex: '@zindex-tooltip',
       display: 'block',
       '$mixin': [ { '.reset-text': [ 0 ] }, { '.opacity': [ 0 ] } ],
       fontSize: '@font-size-small',
       '&.in': { '$mixin': { '.opacity': [ '@tooltip-opacity' ] } },
       '&.top': { marginTop: '-3px', padding: '@tooltip-arrow-width 0' },
       '&.right': { marginLeft: '3px', padding: '0 @tooltip-arrow-width' },
       '&.bottom': { marginTop: '3px', padding: '@tooltip-arrow-width 0' },
       '&.left': { marginLeft: '-3px', padding: '0 @tooltip-arrow-width' } },
     {},
     '&.top .tooltip-arrow': { bottom: 0,
       left: '50%',
       marginLeft: '-@tooltip-arrow-width',
       borderWidth: '@tooltip-arrow-width @tooltip-arrow-width 0',
       borderTopColor: '@tooltip-arrow-color' },
     '&.top-left .tooltip-arrow': { bottom: 0,
       right: '@tooltip-arrow-width',
       marginBottom: '-@tooltip-arrow-width',
       borderWidth: '@tooltip-arrow-width @tooltip-arrow-width 0',
       borderTopColor: '@tooltip-arrow-color' },
     '&.top-right .tooltip-arrow': { bottom: 0,
       left: '@tooltip-arrow-width',
       marginBottom: '-@tooltip-arrow-width',
       borderWidth: '@tooltip-arrow-width @tooltip-arrow-width 0',
       borderTopColor: '@tooltip-arrow-color' },
     '&.right .tooltip-arrow': { top: '50%',
       left: 0,
       marginTop: '-@tooltip-arrow-width',
       borderWidth: '@tooltip-arrow-width @tooltip-arrow-width @tooltip-arrow-width 0',
       borderRightColor: '@tooltip-arrow-color' },
     '&.left .tooltip-arrow': { top: '50%',
       right: 0,
       marginTop: '-@tooltip-arrow-width',
       borderWidth: '@tooltip-arrow-width 0 @tooltip-arrow-width @tooltip-arrow-width',
       borderLeftColor: '@tooltip-arrow-color' },
     '&.bottom .tooltip-arrow': { top: 0,
       left: '50%',
       marginLeft: '-@tooltip-arrow-width',
       borderWidth: '0 @tooltip-arrow-width @tooltip-arrow-width',
       borderBottomColor: '@tooltip-arrow-color' },
     '&.bottom-left .tooltip-arrow': { top: 0,
       right: '@tooltip-arrow-width',
       marginTop: '-@tooltip-arrow-width',
       borderWidth: '0 @tooltip-arrow-width @tooltip-arrow-width',
       borderBottomColor: '@tooltip-arrow-color' },
     '&.bottom-right .tooltip-arrow': { top: 0,
       left: '@tooltip-arrow-width',
       marginTop: '-@tooltip-arrow-width',
       borderWidth: '0 @tooltip-arrow-width @tooltip-arrow-width',
       borderBottomColor: '@tooltip-arrow-color' } ],
  '.tooltip-inner': 
   { maxWidth: '@tooltip-max-width',
     padding: '3px 8px',
     color: '@tooltip-color',
     textAlign: 'center',
     backgroundColor: '@tooltip-bg',
     borderRadius: '@border-radius-base' },
  '.tooltip-arrow': 
   { position: 'absolute',
     width: 0,
     height: 0,
     borderColor: 'transparent',
     borderStyle: 'solid' } }
